# Generated by Django 3.1.2 on 2020-10-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='ip_address',
        ),
    ]
