# Generated by Django 3.1.2 on 2020-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('video', models.URLField()),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
