# Generated by Django 3.1.2 on 2020-10-02 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, default=1, upload_to='media/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
