# Generated by Django 3.1.2 on 2020-10-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20201006_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='video',
        ),
    ]
