# Generated by Django 3.1.2 on 2020-10-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20201006_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
