# Generated by Django 3.1.2 on 2020-10-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_remove_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
