# Generated by Django 3.1.2 on 2020-10-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_auto_20201006_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
